Repository BigMacintosh/Parking, pull requests merged in 2019-12, with the labels that each got.

#52 Add two way player location sync
  ProjectFiles/Assets/Scripts/Game/ClientGameLoop.cs
  ProjectFiles/Assets/Scripts/Game/ServerGameLoop.cs
  ProjectFiles/Assets/Scripts/Game/World.cs
  ProjectFiles/Assets/Scripts/Network/Client.cs
  ProjectFiles/Assets/Scripts/Network/NetworkEvents.cs
  ProjectFiles/Assets/Scripts/Network/Server.cs
Labels: key feature, network

#55 Remove multiplayer from extraeditor script
  extraeditor.sh
Labels: bug

#50 Fix HUD to dynamically add to controllable car.
  ProjectFiles/Assets/Resources/Canvas.prefab
  ProjectFiles/Assets/Resources/Canvas.prefab.meta
  ProjectFiles/Assets/Scenes/TestScene.unity
  ProjectFiles/Assets/Scripts/Car/DriveController.cs
  ProjectFiles/Assets/Scripts/Game/ClientGameLoop.cs
  ProjectFiles/Assets/Scripts/Game/Spawner.cs
  ProjectFiles/Assets/Scripts/Game/Spawner.cs.meta
  ProjectFiles/Assets/Scripts/HUD.cs
Labels: bug

#56 Refactor of drive controller
  ProjectFiles/Assets/Resources/Car.prefab
  ProjectFiles/Assets/Scenes/TestScene.unity
  ProjectFiles/Assets/Scripts/Car/DriveController.cs
  ProjectFiles/Assets/Scripts/Game/World.cs
  ProjectFiles/Assets/Scripts/HUD.cs
  ProjectFiles/Assets/Scripts/Vehicle.meta
  ProjectFiles/Assets/Scripts/Vehicle/AntiRoll.cs
  ProjectFiles/Assets/Scripts/Vehicle/AntiRoll.cs.meta
  ProjectFiles/Assets/Scripts/Vehicle/DriveController.cs
  ProjectFiles/Assets/Scripts/Vehicle/DriveController.cs.meta
  ProjectFiles/Assets/Scripts/Vehicle/SelfRighting.cs
  ProjectFiles/Assets/Scripts/Vehicle/SelfRighting.cs.meta
  ProjectFiles/Assets/Scripts/Vehicle/Vehicle.cs
  ProjectFiles/Assets/Scripts/Vehicle/Vehicle.cs.meta
Labels: mechanic, refactor

#57 Adding the files from the Roadster branch to do a pull request
  ProjectFiles/Assets/Materials/Road.mat
  ProjectFiles/Assets/Materials/Road.mat.meta
  ProjectFiles/Assets/Textures/road.psd
  ProjectFiles/Assets/Textures/road.psd.meta
  ProjectFiles/Assets/Tools.meta
  ProjectFiles/Assets/Tools/Roadster.meta
  ProjectFiles/Assets/Tools/Roadster/Bezier.cs
  ProjectFiles/Assets/Tools/Roadster/Bezier.cs.meta
  ProjectFiles/Assets/Tools/Roadster/BezierSpline.cs
  ProjectFiles/Assets/Tools/Roadster/BezierSpline.cs.meta
  ProjectFiles/Assets/Tools/Roadster/Editor.meta
  ProjectFiles/Assets/Tools/Roadster/Editor/BezierSplineInspector.cs
  ProjectFiles/Assets/Tools/Roadster/Editor/BezierSplineInspector.cs.meta
  ProjectFiles/Assets/Tools/Roadster/Editor/LineInspector.cs
  ProjectFiles/Assets/Tools/Roadster/Editor/LineInspector.cs.meta
  ProjectFiles/Assets/Tools/Roadster/Line.cs
  ProjectFiles/Assets/Tools/Roadster/Line.cs.meta
  ProjectFiles/Assets/Tools/Roadster/Paver.cs
  ProjectFiles/Assets/Tools/Roadster/Paver.cs.meta
  ProjectFiles/Assets/Tools/Roadster/SplineDecorator.cs
  ProjectFiles/Assets/Tools/Roadster/SplineDecorator.cs.meta
Labels: enhancement, map design

#61 Escape key closes the game
  ProjectFiles/Assets/Scripts/Game/Game.cs
Labels: enhancement
