Repository BigMacintosh/Parking, pull requests merged in 2020-02, with the labels that each got.

#83 Car Model + Roadster tweaks
  ProjectFiles/Assets/Materials/Vehicles.meta
  ProjectFiles/Assets/Materials/Vehicles/Hatchback.meta
  ProjectFiles/Assets/Materials/Vehicles/Hatchback/Body.mat
  ProjectFiles/Assets/Materials/Vehicles/Hatchback/Body.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Hatchback/Lights.mat
  ProjectFiles/Assets/Materials/Vehicles/Hatchback/Lights.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Hatchback/Metallics.mat
  ProjectFiles/Assets/Materials/Vehicles/Hatchback/Metallics.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Hatchback/Wheels.mat
  ProjectFiles/Assets/Materials/Vehicles/Hatchback/Wheels.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Hatchback/Windows.mat
  ProjectFiles/Assets/Materials/Vehicles/Hatchback/Windows.mat.meta
  ProjectFiles/Assets/Models/Vehicles.meta
  ProjectFiles/Assets/Models/Vehicles/Hatchback.blend
  ProjectFiles/Assets/Models/Vehicles/Hatchback.blend.meta
  ProjectFiles/Assets/Models/Vehicles/Hatchback.blend1
  ProjectFiles/Assets/Models/Vehicles/Hatchback.blend1.meta
  ProjectFiles/Assets/Resources/Car.prefab
  ProjectFiles/Assets/Scenes/RaceTrack.unity
  ProjectFiles/Assets/Scenes/TestScene.unity
  ProjectFiles/Assets/Tools/Roadster/BezierSpline.cs
Labels: map design

#81 Add round manager
  ProjectFiles/Assets/Scripts/Game/ClientGameLoop.cs
  ProjectFiles/Assets/Scripts/Game/RoundManager.cs
  ProjectFiles/Assets/Scripts/Game/RoundManager.cs.meta
  ProjectFiles/Assets/Scripts/Game/ServerGameLoop.cs
  ProjectFiles/Assets/Scripts/Game/World.cs
  ProjectFiles/Assets/Scripts/Network/Client.cs
  ProjectFiles/Assets/Scripts/Network/Events/ServerEliminatePlayersEvent.cs
  ProjectFiles/Assets/Scripts/Network/Events/ServerPreRoundStartEvent.cs
  ProjectFiles/Assets/Scripts/Network/Events/ServerRoundEndEvent.cs
  ProjectFiles/Assets/Scripts/Network/Events/ServerRoundStartEvent.cs
  ProjectFiles/Assets/Scripts/Network/Server.cs
  ProjectFiles/ProjectFiles.sln.DotSettings
Labels: key feature, round-manager

#87 Jumping
  ProjectFiles/Assets/Resources/Car.prefab
  ProjectFiles/Assets/Scripts/Vehicle/VehicleDriver.cs
Labels: enhancement

#86 Add spawn locations menu to the game gameobject
  ProjectFiles/Assets/Scenes/TestScene.unity
  ProjectFiles/Assets/Scripts/Game/Game.cs
  ProjectFiles/Assets/Scripts/Game/World.cs
Labels: IMPORTANT, bug

#107 Disconnect fixes
  ProjectFiles/.gitignore
  ProjectFiles/Assets/Scripts/Game/ClientGameLoop.cs
  ProjectFiles/Assets/Scripts/Network/Server.cs
  ProjectFiles/ProjectSettings/EditorBuildSettings.asset
  ProjectFiles/ProjectSettings/UnityConnectSettings.asset
  ProjectFiles/server-config.json
Labels: network

#121 Collider Fixes
  ProjectFiles/Assets/Resources/Car.prefab
  ProjectFiles/Assets/Scripts/Vehicle/VehicleDriver.cs
Labels: bug, car controls, enhancement

#122 Fix texture issues on mac
  ProjectFiles/Assets/Materials/Terrain.mat
  ProjectFiles/Assets/Scenes/ModelShowcase.unity
Labels: bug

#129 Add script to make building for client and server easier
  .gitignore
  ProjectFiles/Assets/Editor.meta
  ProjectFiles/Assets/Editor/ServerBuild.cs
  ProjectFiles/Assets/Editor/ServerBuild.cs.meta
  ProjectFiles/Assets/Scripts/Game/Game.cs
  build.sh
Labels: enhancement

#127 Disconnect event
  ProjectFiles/Assets/Scripts/Network/Client.cs
  ProjectFiles/Assets/Scripts/Network/EventType.cs
  ProjectFiles/Assets/Scripts/Network/Events/ServerDisconnectEvent.cs
  ProjectFiles/Assets/Scripts/Network/Events/ServerDisconnectEvent.cs.meta
  ProjectFiles/Assets/Scripts/Network/Server.cs
Labels: bug, mechanic

#133 Basic Minimap
  ProjectFiles/Assets/Resources/Car.prefab
  ProjectFiles/Assets/Resources/Minimap Canvas.prefab
  ProjectFiles/Assets/Resources/Minimap Canvas.prefab.meta
  ProjectFiles/Assets/Scenes/ModelShowcase.unity
  ProjectFiles/Assets/Scripts/Game/ClientGameLoop.cs
  ProjectFiles/Assets/Scripts/SceneUtilities.meta
  ProjectFiles/Assets/Scripts/SceneUtilities/MinimapController.cs
  ProjectFiles/Assets/Scripts/SceneUtilities/MinimapController.cs.meta
  ProjectFiles/Assets/Scripts/Vehicle/Vehicle.cs
  ProjectFiles/Assets/Textures/mask.png
  ProjectFiles/Assets/Textures/mask.png.meta
  ProjectFiles/Assets/Textures/maskFeather.png
  ProjectFiles/Assets/Textures/maskFeather.png.meta
  ProjectFiles/Assets/Textures/minimap-texture.renderTexture
  ProjectFiles/Assets/Textures/minimap-texture.renderTexture.meta
  ProjectFiles/ProjectSettings/GraphicsSettings.asset
Labels: enhancement, game interface

#134 Moves the location of the network delegates
  ProjectFiles/.gitignore
  ProjectFiles/Assets/Scripts/Network/Client.cs
  ProjectFiles/Assets/Scripts/Network/NetworkDelegates.cs
  ProjectFiles/Assets/Scripts/Network/NetworkDelegates.cs.meta
  ProjectFiles/ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: network, round-manager

#149 Add admin menu for starting a game
  ProjectFiles/Assets/Resources/UICanvas.prefab
  ProjectFiles/Assets/Scenes/MainMenu.unity
  ProjectFiles/Assets/Scenes/ModelShowcase.unity
  ProjectFiles/Assets/Scripts/Game/ClientGameLoop.cs
  ProjectFiles/Assets/Scripts/Game/RoundManager.cs
  ProjectFiles/Assets/Scripts/Game/ServerGameLoop.cs
  ProjectFiles/Assets/Scripts/Network/Client.cs
  ProjectFiles/Assets/Scripts/Network/ClientConfig.cs
  ProjectFiles/Assets/Scripts/Network/DummyClient.cs
  ProjectFiles/Assets/Scripts/Network/EventType.cs
  ProjectFiles/Assets/Scripts/Network/Events/AdminClientStartGameEvent.cs
  ProjectFiles/Assets/Scripts/Network/Events/AdminClientStartGameEvent.cs.meta
  ProjectFiles/Assets/Scripts/Network/Events/ClientHandshakeEvent.cs
  ProjectFiles/Assets/Scripts/Network/NetworkDelegates.cs
  ProjectFiles/Assets/Scripts/Network/Server.cs
  ProjectFiles/Assets/Scripts/UI/AdminMenu.cs
  ProjectFiles/Assets/Scripts/UI/AdminMenu.cs.meta
  ProjectFiles/Assets/Scripts/UI/MainMenu/AdminModeButton.cs
  ProjectFiles/Assets/Scripts/UI/MainMenu/AdminModeButton.cs.meta
  ProjectFiles/Assets/Scripts/UI/UIController.cs
Labels: game interface

#156 Add player spawning in more sensible places
  ProjectFiles/Assets/Polybrush Data/Prefab Palette/PrefabPalette-Default.asset
  ProjectFiles/Assets/Scripts/Game/ClientGameLoop.cs
  ProjectFiles/Assets/Scripts/Game/ServerGameLoop.cs
  ProjectFiles/Assets/Scripts/Game/World.cs
  ProjectFiles/Assets/Scripts/Gameplay/ParkingSpaceManager.cs
  ProjectFiles/Assets/Scripts/Gameplay/PlayerSpawner.cs
  ProjectFiles/Assets/Scripts/Gameplay/PlayerSpawner.cs.meta
Labels: spaces, spawning

#160 Vehicle models
  ProjectFiles/Assets/Animations.meta
  ProjectFiles/Assets/Animations/Vehicles.meta
  ProjectFiles/Assets/Animations/Vehicles/PoliceLightController.controller
  ProjectFiles/Assets/Animations/Vehicles/PoliceLightController.controller.meta
  ProjectFiles/Assets/Animations/Vehicles/PoliceLights.anim
  ProjectFiles/Assets/Animations/Vehicles/PoliceLights.anim.meta
  ProjectFiles/Assets/Materials/Vehicles/Lights.mat
  ProjectFiles/Assets/Materials/Vehicles/Lights.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Metallics.mat
  ProjectFiles/Assets/Materials/Vehicles/Metallics.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Police.meta
  ProjectFiles/Assets/Materials/Vehicles/Police/BodyBlack.mat
  ProjectFiles/Assets/Materials/Vehicles/Police/BodyBlack.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Police/BodyWhite.mat
  ProjectFiles/Assets/Materials/Vehicles/Police/BodyWhite.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Police/Bumper.mat
  ProjectFiles/Assets/Materials/Vehicles/Police/Bumper.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Police/TopLight.mat
  ProjectFiles/Assets/Materials/Vehicles/Police/TopLight.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/RearLight.mat
  ProjectFiles/Assets/Materials/Vehicles/RearLight.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Wheels.mat
  ProjectFiles/Assets/Materials/Vehicles/Wheels.mat.meta
  ProjectFiles/Assets/Materials/Vehicles/Windows.mat
  ProjectFiles/Assets/Materials/Vehicles/Windows.mat.meta
  ProjectFiles/Assets/Models/Vehicles/Hatchback.blend
  ProjectFiles/Assets/Models/Vehicles/Hatchback.blend1
  ProjectFiles/Assets/Models/Vehicles/Police.blend
  ProjectFiles/Assets/Models/Vehicles/Police.blend.meta
  ProjectFiles/Assets/Models/Vehicles/Police.blend1
  ProjectFiles/Assets/Models/Vehicles/Police.blend1.meta
  ProjectFiles/Assets/Resources/Car.prefab
  ProjectFiles/Assets/Resources/Police.prefab
  ProjectFiles/Assets/Resources/Police.prefab.meta
  ProjectFiles/Assets/Scenes/ModelShowcase.unity
  ProjectFiles/Assets/Scripts/Vehicle/DriveWheel.cs
  ProjectFiles/Assets/Scripts/Vehicle/PoliceLight.cs
  ProjectFiles/Assets/Scripts/Vehicle/PoliceLight.cs.meta
  ProjectFiles/Assets/Textures/79777bc9bd7bc0ff1b4fd3efa865948a.jpg
  ProjectFiles/Assets/Textures/79777bc9bd7bc0ff1b4fd3efa865948a.jpg.meta
  ProjectFiles/Assets/Textures/PoliceFlare.flare
  ProjectFiles/Assets/Textures/PoliceFlare.flare.meta
  ProjectFiles/ProjectSettings/GraphicsSettings.asset
  ProjectFiles/ProjectSettings/InputManager.asset
  ProjectFiles/ProjectSettings/Packages/com.unity.probuilder/Settings.json
  ProjectFiles/ProjectSettings/ProjectSettings.asset
  ProjectFiles/ProjectSettings/TagManager.asset
Labels: enhancement

#177 hudhud
  ProjectFiles/Assets/Resources/UICanvas.prefab
  ProjectFiles/Assets/Scripts/Game/ClientGameLoop.cs
  ProjectFiles/Assets/Scripts/Game/World.cs
  ProjectFiles/Assets/Scripts/Gameplay/ParkingSpaceManager.cs
  ProjectFiles/Assets/Scripts/Network/Client.cs
  ProjectFiles/Assets/Scripts/Network/ClientConfig.cs
  ProjectFiles/Assets/Scripts/Network/DummyClient.cs
  ProjectFiles/Assets/Scripts/Network/Events/ClientLocationUpdateEvent.cs
  ProjectFiles/Assets/Scripts/Network/Events/ServerLocationUpdateEvent.cs
  ProjectFiles/Assets/Scripts/UI/HUD.cs
  ProjectFiles/Assets/Scripts/UI/UIController.cs
  ProjectFiles/Assets/Scripts/UI/UIDelegates.cs
  ProjectFiles/Assets/Scripts/UI/UIDelegates.cs.meta
Labels: game interface
