Repository BigMacintosh/Parking, pull requests merged in 2020-03, with the labels that each got.

#213 Destroy Indicator
  ProjectFiles/Assets/Resources/Minimap Canvas.prefab
  ProjectFiles/Assets/Scripts/UI/Minimap/MinimapScroller.cs
  ProjectFiles/Assets/Scripts/UI/Minimap/RenderToMinimap.cs
Labels: bug, minimap

#214 Hotfix for incorrect deserialization of ServerGameEndEvent
  ProjectFiles/Assets/Scripts/Network/Events/ServerEliminatePlayersEvent.cs
  ProjectFiles/Assets/Scripts/Network/Events/ServerGameEndEvent.cs
Labels: bug

#219 Car indicator
  ProjectFiles/Assets/Resources/Car.prefab
  ProjectFiles/Assets/Resources/Space.prefab
  ProjectFiles/Assets/Scripts/Network/Client.cs
  ProjectFiles/Assets/Scripts/UI/Minimap/MinimapController.cs
  ProjectFiles/Assets/Scripts/UI/Minimap/MinimapController.cs.meta
  ProjectFiles/Assets/Scripts/UI/Minimap/RenderToMinimap.cs
  ProjectFiles/Assets/Textures/Minimap/car.png
  ProjectFiles/Assets/Textures/Minimap/car.png.meta
Labels: minimap

#223 Hot fix for escape key crashing the game
  ProjectFiles/Assets/Scripts/Game/Main/Game.cs
Labels: bug

#225 Hot fix for build script
  build.sh
Labels: bug

#220 Collisions
  ProjectFiles/Assets/Resources/Car.prefab
  ProjectFiles/Assets/Scripts/EditorTools/Roadster.meta
  ProjectFiles/Assets/Scripts/Game/Core/Driving/DriveWheel.cs
  ProjectFiles/Assets/Scripts/Game/Core/Driving/Vehicle.cs
  ProjectFiles/Assets/Scripts/Game/Core/Driving/VehicleDriver.cs
  ProjectFiles/Assets/Tools/Roadster/Editor.meta
Labels: car controls

#230 Adds support in the world for eliminating players
  ProjectFiles/Assets/Scripts/Game/Entity/ClientWorld.cs
  ProjectFiles/Assets/Scripts/Game/Entity/Player.cs
  ProjectFiles/Assets/Scripts/Game/Entity/ServerWorld.cs
  ProjectFiles/Assets/Scripts/Game/Entity/SpawnLocations.cs
  ProjectFiles/Assets/Scripts/Game/Entity/World.cs
  ProjectFiles/Assets/Scripts/Game/Main/ClientGameLoop.cs
  ProjectFiles/Assets/Scripts/Game/Main/Game.cs
  ProjectFiles/Assets/Scripts/Game/Main/ServerGameLoop.cs
Labels: world

#256 Quick fix for build errors
  ProjectFiles/Assets/Editor/Build.meta
  ProjectFiles/Assets/Editor/Build/Build.cs
  ProjectFiles/Assets/Editor/Build/Build.cs.meta
  ProjectFiles/Assets/Editor/Roadster.meta
  ProjectFiles/Assets/Editor/Roadster/BezierSplineInspector.cs
  ProjectFiles/Assets/Editor/Roadster/BezierSplineInspector.cs.meta
  ProjectFiles/Assets/Editor/Roadster/LineInspector.cs
  ProjectFiles/Assets/Editor/Roadster/LineInspector.cs.meta
  ProjectFiles/Assets/Editor/Roadster/PaverInspector.cs
  ProjectFiles/Assets/Editor/Roadster/PaverInspector.cs.meta
  ProjectFiles/Assets/Scenes/ModelShowcase.unity
  ProjectFiles/Assets/Scripts/EditorTools.meta
  ProjectFiles/Assets/Scripts/EditorTools/Roadster/Editor.meta
  ProjectFiles/Assets/Scripts/Roadster.meta
  ProjectFiles/Assets/Scripts/Roadster/Bezier.cs
  ProjectFiles/Assets/Scripts/Roadster/Bezier.cs.meta
  ProjectFiles/Assets/Scripts/Roadster/BezierSpline.cs
  ProjectFiles/Assets/Scripts/Roadster/BezierSpline.cs.meta
  ProjectFiles/Assets/Scripts/Roadster/Line.cs
  ProjectFiles/Assets/Scripts/Roadster/Line.cs.meta
  ProjectFiles/Assets/Scripts/Roadster/Paver.cs
  ProjectFiles/Assets/Scripts/Roadster/Paver.cs.meta
  ProjectFiles/Assets/Scripts/Roadster/SplineDecorator.cs
  ProjectFiles/Assets/Scripts/Roadster/SplineDecorator.cs.meta
  ProjectFiles/Assets/Scripts/Tests.meta
Labels: bug

#257 Renderer fix
  ProjectFiles/Assets/Settings/Renderer.asset
  ProjectFiles/Assets/Settings/Renderer.asset.meta
  ProjectFiles/Assets/Settings/RendererForward.asset
  ProjectFiles/Assets/Settings/RendererForward.asset.meta
  ProjectFiles/Assets/Tools.meta
  ProjectFiles/Assets/Tools/Roadster.meta
  ProjectFiles/Assets/Tools/Roadster/Editor.meta
Labels: bug
